version: '2'
services:
  process2021-app:
    image: process2021
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://process2021-postgresql:5432/process2021
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  process2021-postgresql:
    extends:
      file: postgresql.yml
      service: process2021-postgresql
